---

- name: Include OS-specific Variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Check if MariaDB Repo Exists
  stat: path={{ mariadb_repo_file_path }}
  register: mariadb_repo_file_result

- name: Install the MariaDB Repo
  yum_repository:
    name: MariaDB
    description: MariaDB Repo
    baseurl: "{{ mariadb_repo_url }}"
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10
  when: not mariadb_repo_file_result.stat.exists

- name: Make Sure the MariaDB GPG Key is Imported
  rpm_key:
    key: "{{ mariadb_repo_gpg_key_url }}"
    state: present
